# This docker compose file defines the hosts on in the network toplogy.
#

# Indiana Subnetwork
services:
  server:
    image: debian:stable

    container_name: server

    hostname: server

    tty: true

    cap_add:
      - ALL

    sysctls:
      - net.ipv4.ip_forward=0

    volumes:
      - ./share:/share

    networks:
      illinois-net:
        ipv4_address: 13.12.1.5

    command: >
      bash -c "
      bash /share/set_up_container.sh &&
      ip route add 11.11.0.0/24 via 13.12.1.2 &&
      tail -f /dev/null
      "
