# This docker compose file defines the hosts on in the network toplogy.
#

# Indiana Subnetwork
services:
  client:
    # Specify which image should this container use.
    # You can use whichever images you like, be sure to adapt your
    # configuration to the images that you select
    image: debian:stable

    # The name of the container that will show up in `docker compose ps`
    container_name: client

    # The hostname for this container - will be used in configuring it.
    # This is the hostname that will be used for this container in dns lookups
    # as well as what will be returned to the command hostname.
    hostname: client

    # Should this container occupy a tty?
    tty: true

    # The starting working directory for this container.
    # Omitting this will always start at $HOME.
    # working_dir: /volumes/

    # Specify the capabilities that this container should have.
    #  For specifically these labs, ALL is good. But you'd want to be more
    #  conservative when dealing with other containers.
    cap_add:
      - ALL

    sysctls:
      - net.ipv4.ip_forward=0

    # This property specifies which files from your LOCAL directory will be
    # mounted in the container. The container by default will have both read
    # and write access to this mounted directory.
    volumes:
      - ./share:/share

    # Which networks do you want to hook this container up to.
    # By default, interfaces start from `eth0`.
    networks:
      # This network must be defined in the networks property below!
      indiana-net:
        # Specifiy a static IPv4 address for this container on this network.
        ipv4_address: 11.11.0.2

    # This command contains everything that should be executed once the
    # container is about to be launched.
    #
    # WARNING: A failure here means that your container will not continue to
    # live, it will be automatic terminated.
    #
    # To see logs from these commands, use the `dcl` alias

      # bash -c "
    command: >
      bash /share/set_up_container.sh

    #
    # OTHER PROPERTIES
    #
    # extra_hosts:
    #   Add any additional host to IP mapping you want to use in your container
    #   For example:
    #     server: "10.10.1.5"
    #
    # sysctls:
    #   Any system control configuration goes here. This can edit some of the
    #   thing you can change using systemctl
